# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-05 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20170805_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='image',
            new_name='photo',
        ),
    ]
