# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-05 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20170805_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='photo',
        ),
        migrations.AddField(
            model_name='feed',
            name='cat',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
