# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-05 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20170805_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='cat',
        ),
        migrations.AddField(
            model_name='feed',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='photo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='imagePosts/', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='feed',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
