# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-05 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_auto_20170805_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='feed',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='imagePosts/'),
        ),
    ]
