# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-05 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_auto_20170805_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='height_field',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='width_field',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='photo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='imagePosts/', width_field='width_field'),
        ),
    ]
