# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-05 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_auto_20170805_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='imagePosts/'),
        ),
    ]
