# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-06 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_auto_20170805_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='width_field',
        ),
    ]
