# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-08 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0014_auto_20170806_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='content',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
