# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_feed_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='content',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
    ]
