# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-09 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_auto_20170808_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='content',
        ),
    ]
